Document: scimpy
Title: Debian scimpy Manual
Author: <insert document author here>
Abstract: This manual describes what scimpy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scimpy/scimpy.sgml.gz

Format: postscript
Files: /usr/share/doc/scimpy/scimpy.ps.gz

Format: text
Files: /usr/share/doc/scimpy/scimpy.text.gz

Format: HTML
Index: /usr/share/doc/scimpy/html/index.html
Files: /usr/share/doc/scimpy/html/*.html
